BrillouinMicroscopy/BrillouinAcquisition

BrillouinAcquisition/BrillouinAcquisition.cpp
BrillouinAcquisition/BrillouinAcquisition.h
BrillouinAcquisition/andor.cpp
BrillouinAcquisition/andor.h
BrillouinAcquisition/scancontrol.cpp
BrillouinAcquisition/scancontrol.h
BrillouinAcquisitionUnitTest/unittest1.cpp

Check if devices are connected correctly, closes #9, #10

---

BrillouinAcquisition/BrillouinAcquisition.cpp
BrillouinAcquisition/BrillouinAcquisition.h
BrillouinAcquisition/BrillouinAcquisition.ui
BrillouinAcquisition/acquisition.cpp
BrillouinAcquisition/acquisition.h
BrillouinAcquisition/andor.cpp
BrillouinAcquisition/andor.h
BrillouinAcquisition/circularBuffer.h
BrillouinAcquisition/previewBuffer.h

Implement repeated measurements, closes #22

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.cpp

This fixes the vector containing the positions written to the HDF5 file.

Fix positions vector

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.h
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/BrillouinAcquisition.h
BrillouinAcquisition/src/BrillouinAcquisition.ui
BrillouinAcquisition/src/Devices/Camera.h
BrillouinAcquisition/src/Devices/PointGrey.cpp
BrillouinAcquisition/src/Devices/PointGrey.h
BrillouinAcquisition/src/Devices/andor.cpp
BrillouinAcquisition/src/Devices/andor.h
BrillouinAcquisition/src/Devices/uEyeCam.cpp
BrillouinAcquisition/src/Devices/uEyeCam.h

Adds the possibility to preview the fluorescence channels. It also shows the acquired fluorescence images and allows to acquire a single channel by button click.

Fluorescence preview, closes #74

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/Devices/Camera.h
BrillouinAcquisition/src/Devices/PointGrey.cpp

Minor improvements

---

BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/BrillouinAcquisition.h
BrillouinAcquisition/src/Devices/scancontrol.h

Implement saving settings

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/Camera.cpp
BrillouinAcquisition/src/Devices/pvcamera.cpp

so the compiler can check whether the function can be called

Use lambda expressions in invokeMethod

---

BrillouinAcquisition/src/Devices/ZeissMTB.cpp
BrillouinAcquisition/src/Devices/ZeissMTB_Erlangen.cpp

Don't go 💣 when MTB server is not running

---

BrillouinAcquisition/src/Devices/ZeissMTB_Erlangen.cpp
BrillouinAcquisition/src/Devices/ZeissMTB_Erlangen.h

Implement LED and beam block for Erlangen

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.h
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/uEyeCam.cpp

Restart preview after acquisition on uEye camera

---

BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/andor.cpp
BrillouinAcquisition/src/Devices/pvcamera.cpp
BrillouinAcquisition/src/converter.cpp

Fix binning feature for Andor cameras

---

BrillouinAcquisition/src/Devices/NIDAQ.cpp
BrillouinAcquisition/src/Devices/NIDAQ.h

For some reason the mirror start and end positions have changed. Probably a software issue with the Thorlabs software, needs to be determined.

Adjust mirror positions

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/VoltageCalibration.cpp
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/Cameras/PointGrey.cpp
BrillouinAcquisition/src/Devices/Cameras/andor.cpp
BrillouinAcquisition/src/Devices/Cameras/cameraParameters.h
BrillouinAcquisition/src/Devices/Cameras/pvcamera.cpp
BrillouinAcquisition/src/Devices/Cameras/uEyeCam.cpp
BrillouinAcquisition/src/converter.cpp

Fixes binning with repetitions, closes #142.

Correctly handle physical and binned image size

---

BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/BrillouinAcquisition.h

Ask for confirmation before closing

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp

#144 broke the fluorescence acquisition, this PR fixes it.
Closes #152.

Fix fluorescence acquisition

---

BrillouinAcquisition/src/Devices/Cameras/pvcamera.cpp

Follow-up to #156. Closes #160.

Fix setting PVCam settings

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp

Fix fluo acquisition when preview runs

---

BrillouinAcquisition/src/Acquisition/Acquisition.cpp
BrillouinAcquisition/src/BrillouinAcquisition.cpp

Correctly exit threads

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/Cameras/Camera.h
BrillouinAcquisition/src/Devices/Cameras/andor.cpp
BrillouinAcquisition/src/Devices/Cameras/pvcamera.cpp
BrillouinAcquisition/src/Devices/ScanControls/NIDAQ.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen.cpp
BrillouinAcquisition/src/Devices/filtermount.cpp
BrillouinAcquisition/src/circularBuffer.h
BrillouinAcquisition/src/converter.cpp
BrillouinAcquisition/src/phase.h
BrillouinAcquisition/src/previewBuffer.h
BrillouinAcquisition/src/storageWrapper.cpp
BrillouinAcquisition/src/storageWrapper.h

Correctly delete all variables necessary

---

BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/Cameras/Camera.cpp
BrillouinAcquisition/src/Devices/Cameras/Camera.h
BrillouinAcquisition/src/Devices/Cameras/MockCamera.cpp
BrillouinAcquisition/src/Devices/Cameras/PointGrey.cpp
BrillouinAcquisition/src/Devices/Cameras/andor.cpp
BrillouinAcquisition/src/Devices/Cameras/pvcamera.cpp
BrillouinAcquisition/src/Devices/Cameras/uEyeCam.cpp

Use signals to show new images

---

BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.h

Implement lamp and shutter control for ZeissECU

---

BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen.cpp

Block the laser for eyepiece preset

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.h
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/Fluorescence.h
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ODT.h
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/Cameras/MockCamera.cpp
BrillouinAcquisition/src/Devices/Cameras/PointGrey.cpp
BrillouinAcquisition/src/Devices/Cameras/andor.cpp
BrillouinAcquisition/src/Devices/Cameras/cameraParameters.h
BrillouinAcquisition/src/Devices/Cameras/pvcamera.cpp
BrillouinAcquisition/src/Devices/Cameras/uEyeCam.cpp
BrillouinAcquisition/src/storageWrapper.cpp

Necessary for the scale calibration to work properly.
Requires https://github.com/BrillouinMicroscopy/h5bm/pull/14.
Closes #192.

Implement saving camera ROI data

---

BrillouinAcquisition/src/Devices/ScanControls/NIDAQ.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp

Adjust preview settings

---

BrillouinAcquisition/src/Devices/ScanControls/NIDAQ.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp

With newer versions of Kinesis, the connection to the Thorlabs devices did fail.

Fix connectivity to Thorlabs devices

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/ScaleCalibration.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/VoltageCalibration.cpp
BrillouinAcquisition/src/Acquisition/AcquisitionModes/VoltageCalibration.h
BrillouinAcquisition/src/BrillouinAcquisition.cpp

Closes https://github.com/BrillouinMicroscopy/BrillouinAcquisition/issues/208.

Don't crash if calibration file cannot be written

---

BrillouinAcquisition/BrillouinAcquisition.vcxproj
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissECU.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen2.cpp
BrillouinAcquisitionUnitTest/BrillouinAcquisitionUnitTest.vcxproj
README.md
commonProps/ThirdPartyPaths.props

This PR aims to simplify project compilation using a `.props` file. 
Advantages:
- No need to set the debug and release configurations manually
- Centralized third party dependency configuration management using `.props` file

Simplify project compilation with props

---

BrillouinAcquisition/src/Acquisition/AcquisitionModes/Brillouin.h
BrillouinAcquisition/src/Acquisition/AcquisitionModes/ScaleCalibration.h
BrillouinAcquisition/src/BrillouinAcquisition.cpp
BrillouinAcquisition/src/BrillouinAcquisition.h
BrillouinAcquisition/src/Devices/ScanControls/NIDAQ.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen.cpp
BrillouinAcquisition/src/Devices/ScanControls/ZeissMTB_Erlangen2.cpp
BrillouinAcquisition/src/generateVersionHeader.ps1
CHANGELOG.md

This PR aims to fix the issue raised in PR #253

Fix encoding issue by using correct character (µm)
